# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: "Isacc's Blog"
author: 'isacc'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://isacc-131.github.io/blog/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:
    desc:
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/isacc-131
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:
#    desc:
#    share_url:
#    share_title:
#    share_link:
